<?php include 'header.php'; ?>
<div style="float: right; font-size: 0.8em">&nbsp;<a href="why.php" class="a_back"></a>&nbsp;<a href="why.php"><?php echo _('Why should I move?'); ?></a> | <a href="index.php" class="a_home"></a>&nbsp;|&nbsp;<a href="considerations.php"><?php echo _('Other considerations'); ?></a>&nbsp;<a href="considerations.php" class="a_forward"></a></div>

<h3 id="data"><?php echo _('What about my data?'); ?></h3>
<?php echo _('One of the major hurdles when converting from closed source software is compatibility. Companies which create their own closed source formats make it virtually impossible for anyone else to know how their formats work. Despite this, Linux is compatible with almost every data format in existence and there is generally a freely available program that will read your data. For example, Microsoft Office documents are supported in the <a target="_blank" href="http://openoffice.org">OpenOffice.org</a> suite and Adobe Photoshop files are supported in the <a target="_blank" href="http://gimp.org">Gimp</a>.'); ?><br /><br />

<?php echo _('Linux supports and encourages the use of open source file formats. Currently the majority of documents are created by Microsoft Office, however these formats are closed source and proprietary. Using these formats puts you at the whim of Microsoft who can (and do) make their file formats incompatible with other applications, including older versions of Microsoft Office! Because these files are closed source, people are forced to purchase new versions of Microsoft Office. While some open source office suites can read and write Microsoft formats, the results are sometimes imperfect because we do not have the code to see how the formats work. Still Linux does a great job of working with Microsoft Office files and you will probably find you can use and swap them without issue. You can read more about this topic next in the section of this website, \'<a href="considerations.php#msformats">Other considerations</a>\'.'); ?><br /><br />

<?php echo _('As a result the free community has adopted a new <a target="_blank"href="http://www.iso.org">International Organization for Standarization</a> (ISO) approved XML based document standard (<a target="_blank" href="http://www.iso.org/iso/en/commcentre/pressreleases/2006/Ref1004.html">ISO26300</a>) from OASIS called \'<a target="_blank" href="http://www.oasis-open.org/committees/tc_home.php?wg_abbrev=office">open document</a>\'. This standard is freely available for anyone to learn and implement (yes, even Microsoft) because it is open source. Due to pressure applied by various Governments switching to this new open format, Microsoft was forced to support this format in their next version of Office. We are not sure to what degree they will support it, however OpenOffice.org already does. Aside from the new open document formats, there are many other formats you can use that are freely usable; HTML, PDF, and even plain text.'); ?><br /><br />

<?php echo _('As the ISO states, <em>"Organizations and individuals that store their data in the open format avoid being  locked in to a single software vendor, leaving them free to switch software if their current vendor goes out-of-business, raises its prices, changes its software, or alters its  licensing terms"</em>. <br /><br />Organisations all around the world, including the National Archives of Australia, are switching their documents to this new format to ensure unrestricted access to digital information now and in the future. We encourage users to switch from using closed and dangerous proprietary formats to open and freely available formats, which will be around forever.'); ?><br /><br />

<div style="float: right; font-size: 0.8em">&nbsp;<a href="why.php" class="a_back"></a>&nbsp;<a href="why.php"><?php echo _('Why should I move?'); ?></a> | <a href="index.php" class="a_home"></a>&nbsp;|&nbsp;<a href="considerations.php"><?php echo _('Other considerations'); ?></a>&nbsp;<a href="considerations.php" class="a_forward"></a></div>
<br />

<?php include 'footer.php'; ?>
